// Code generated by go-yaml-nillable generator; DO NOT EDIT.

package yamlnillable

// Float32 is a data type for nillable float32 value for YAML marshaling/unmarshaling.
type Float32 struct {
	Val        float32
	IsAssigned bool
}

// Float32Of makes a non-nil value with given float32.
func Float32Of(val float32) *Float32 {
	return &Float32{Val: val, IsAssigned: true}
}

// MarshalYAML marshals Float32 as YAML.
// This method used on marshaling YAML internally.
func (v *Float32) MarshalYAML() (interface{}, error) {
	if v.IsAssigned {
		return v.Val, nil
	}
	return nil, nil
}

// UnarshalYAML unmarshals Float32 as YAML.
// This method used on unmarshaling YAML internally.
func (v *Float32) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var val float32
	if err := unmarshal(&val); err != nil {
		return err
	}
	v.Val = val
	v.IsAssigned = true
	return nil
}
