// Code generated by go-yaml-nillable generator; DO NOT EDIT.

package yamlnillable

// Float64 is a data type for nillable float64 value for YAML marshaling/unmarshaling.
type Float64 struct {
	Val        float64
	IsAssigned bool
}

// Float64Of makes a non-nil value with given float64.
func Float64Of(val float64) *Float64 {
	return &Float64{Val: val, IsAssigned: true}
}

// MarshalYAML marshals Float64 as YAML.
// This method used on marshaling YAML internally.
func (v *Float64) MarshalYAML() (interface{}, error) {
	if v.IsAssigned {
		return v.Val, nil
	}
	return nil, nil
}

// UnarshalYAML unmarshals Float64 as YAML.
// This method used on unmarshaling YAML internally.
func (v *Float64) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var val float64
	if err := unmarshal(&val); err != nil {
		return err
	}
	v.Val = val
	v.IsAssigned = true
	return nil
}
