// Code generated by go-yaml-nillable generator; DO NOT EDIT.

package yamlnillable

// Int is a data type for nillable int value for YAML marshaling/unmarshaling.
type Int struct {
	val        int
	isAssigned bool
}

// IntOf makes a non-nil value with given int.
func IntOf(val int) *Int {
	return &Int{val: val, isAssigned: true}
}

// MarshalYAML marshals Int as YAML.
// This method used on marshaling YAML internally.
func (v *Int) MarshalYAML() (interface{}, error) {
	if v.isAssigned {
		return v.val, nil
	}
	return nil, nil
}

// UnarshalYAML unmarshals Int as YAML.
// This method used on unmarshaling YAML internally.
func (v *Int) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var val int
	if err := unmarshal(&val); err != nil {
		return err
	}
	v.val = val
	v.isAssigned = true
	return nil
}
