// Code generated by go-yaml-nillable generator; DO NOT EDIT.

package yamlnillable

// Int32 is a data type for nillable int32 value for YAML marshaling/unmarshaling.
type Int32 struct {
	Val        int32
	IsAssigned bool
}

// Int32Of makes a non-nil value with given int32.
func Int32Of(val int32) *Int32 {
	return &Int32{Val: val, IsAssigned: true}
}

// MarshalYAML marshals Int32 as YAML.
// This method used on marshaling YAML internally.
func (v *Int32) MarshalYAML() (interface{}, error) {
	if v.IsAssigned {
		return v.Val, nil
	}
	return nil, nil
}

// UnarshalYAML unmarshals Int32 as YAML.
// This method used on unmarshaling YAML internally.
func (v *Int32) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var val int32
	if err := unmarshal(&val); err != nil {
		return err
	}
	v.Val = val
	v.IsAssigned = true
	return nil
}
