// Code generated by go-yaml-nillable generator; DO NOT EDIT.

package yamlnillable

// Int64 is a data type for nillable int64 value for YAML marshaling/unmarshaling.
type Int64 struct {
	Val        int64
	IsAssigned bool
}

// Int64Of makes a non-nil value with given int64.
func Int64Of(val int64) *Int64 {
	return &Int64{Val: val, IsAssigned: true}
}

// MarshalYAML marshals Int64 as YAML.
// This method used on marshaling YAML internally.
func (v *Int64) MarshalYAML() (interface{}, error) {
	if v.IsAssigned {
		return v.Val, nil
	}
	return nil, nil
}

// UnarshalYAML unmarshals Int64 as YAML.
// This method used on unmarshaling YAML internally.
func (v *Int64) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var val int64
	if err := unmarshal(&val); err != nil {
		return err
	}
	v.Val = val
	v.IsAssigned = true
	return nil
}
