// Code generated by go-yaml-nillable generator; DO NOT EDIT.

package yamlnillable

// Rune is a data type for nillable rune value for YAML marshaling/unmarshaling.
type Rune struct {
	Val        rune
	IsAssigned bool
}

// RuneOf makes a non-nil value with given rune.
func RuneOf(val rune) *Rune {
	return &Rune{Val: val, IsAssigned: true}
}

// MarshalYAML marshals Rune as YAML.
// This method used on marshaling YAML internally.
func (v *Rune) MarshalYAML() (interface{}, error) {
	if v.IsAssigned {
		return v.Val, nil
	}
	return nil, nil
}

// UnarshalYAML unmarshals Rune as YAML.
// This method used on unmarshaling YAML internally.
func (v *Rune) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var val rune
	if err := unmarshal(&val); err != nil {
		return err
	}
	v.Val = val
	v.IsAssigned = true
	return nil
}
