// Code generated by go-yaml-nillable generator; DO NOT EDIT.

package yamlnillable

// Rune is a data type for nillable rune value for YAML marshaling/unmarshaling.
type Rune struct {
	val        rune
	isAssigned bool
}

// RuneOf makes a non-nil value with given rune.
func RuneOf(val rune) *Rune {
	return &Rune{val: val, isAssigned: true}
}

// MarshalYAML marshals Rune as YAML.
// This method used on marshaling YAML internally.
func (v *Rune) MarshalYAML() (interface{}, error) {
	if v.isAssigned {
		return v.val, nil
	}
	return nil, nil
}

// UnarshalYAML unmarshals Rune as YAML.
// This method used on unmarshaling YAML internally.
func (v *Rune) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var val rune
	if err := unmarshal(&val); err != nil {
		return err
	}
	v.val = val
	v.isAssigned = true
	return nil
}
