// Code generated by go-yaml-nillable generator; DO NOT EDIT.

package yamlnillable

// String is a data type for nillable string value for YAML marshaling/unmarshaling.
type String struct {
	val        string
	isAssigned bool
}

// StringOf makes a non-nil value with given string.
func StringOf(val string) *String {
	return &String{val: val, isAssigned: true}
}

// MarshalYAML marshals String as YAML.
// This method used on marshaling YAML internally.
func (v *String) MarshalYAML() (interface{}, error) {
	if v.isAssigned {
		return v.val, nil
	}
	return nil, nil
}

// UnarshalYAML unmarshals String as YAML.
// This method used on unmarshaling YAML internally.
func (v *String) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var val string
	if err := unmarshal(&val); err != nil {
		return err
	}
	v.val = val
	v.isAssigned = true
	return nil
}
