// Code generated by go-yaml-nillable generator; DO NOT EDIT.

package yamlnillable

// Uint is a data type for nillable uint value for YAML marshaling/unmarshaling.
type Uint struct {
	Val        uint
	IsAssigned bool
}

// UintOf makes a non-nil value with given uint.
func UintOf(val uint) *Uint {
	return &Uint{Val: val, IsAssigned: true}
}

// MarshalYAML marshals Uint as YAML.
// This method used on marshaling YAML internally.
func (v *Uint) MarshalYAML() (interface{}, error) {
	if v.IsAssigned {
		return v.Val, nil
	}
	return nil, nil
}

// UnarshalYAML unmarshals Uint as YAML.
// This method used on unmarshaling YAML internally.
func (v *Uint) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var val uint
	if err := unmarshal(&val); err != nil {
		return err
	}
	v.Val = val
	v.IsAssigned = true
	return nil
}
