// Code generated by go-yaml-nillable generator; DO NOT EDIT.

package yamlnillable

// Uint32 is a data type for nillable uint32 value for YAML marshaling/unmarshaling.
type Uint32 struct {
	val        uint32
	isAssigned bool
}

// Uint32Of makes a non-nil value with given uint32.
func Uint32Of(val uint32) *Uint32 {
	return &Uint32{val: val, isAssigned: true}
}

// MarshalYAML marshals Uint32 as YAML.
// This method used on marshaling YAML internally.
func (v *Uint32) MarshalYAML() (interface{}, error) {
	if v.isAssigned {
		return v.val, nil
	}
	return nil, nil
}

// UnarshalYAML unmarshals Uint32 as YAML.
// This method used on unmarshaling YAML internally.
func (v *Uint32) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var val uint32
	if err := unmarshal(&val); err != nil {
		return err
	}
	v.val = val
	v.isAssigned = true
	return nil
}
