// Code generated by go-yaml-nillable generator; DO NOT EDIT.

package yamlnillable

// Uint8 is a data type for nillable uint8 value for YAML marshaling/unmarshaling.
type Uint8 struct {
	Val        uint8
	IsAssigned bool
}

// Uint8Of makes a non-nil value with given uint8.
func Uint8Of(val uint8) *Uint8 {
	return &Uint8{Val: val, IsAssigned: true}
}

// MarshalYAML marshals Uint8 as YAML.
// This method used on marshaling YAML internally.
func (v *Uint8) MarshalYAML() (interface{}, error) {
	if v.IsAssigned {
		return v.Val, nil
	}
	return nil, nil
}

// UnarshalYAML unmarshals Uint8 as YAML.
// This method used on unmarshaling YAML internally.
func (v *Uint8) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var val uint8
	if err := unmarshal(&val); err != nil {
		return err
	}
	v.Val = val
	v.IsAssigned = true
	return nil
}
